# Generated by Django 5.2.9 on 2025-12-08 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(help_text="Unique identifier (e.g., 'core_dap')", max_length=50, unique=True)),
                ('name', models.CharField(help_text="Display name (e.g., 'Distemper, Adenovirus, Parvovirus (DAP)')", max_length=100)),
                ('vaccine_type', models.CharField(choices=[('core', 'Core'), ('core_conditional', 'Core Conditional'), ('noncore', 'Non-Core')], help_text='Vaccine category', max_length=20)),
                ('min_start_age_weeks', models.IntegerField(blank=True, help_text='Minimum age in weeks to start this vaccine', null=True)),
                ('rules_json', models.JSONField(help_text='Vaccination rules from vaccine_rules.json')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this vaccine is currently available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vaccine',
                'verbose_name_plural': 'Vaccines',
                'db_table': 'vaccines',
                'ordering': ['vaccine_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_administered', models.DateField(help_text='Date the vaccine was given')),
                ('dose_number', models.IntegerField(blank=True, help_text='Dose number in the series (optional)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the vaccination')),
                ('administered_by', models.CharField(blank=True, help_text='Name of veterinarian or clinic', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dog', models.ForeignKey(help_text='Dog that received the vaccination', on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='patients.dog')),
                ('vaccine', models.ForeignKey(help_text='Vaccine that was administered', on_delete=django.db.models.deletion.PROTECT, related_name='records', to='vaccinations.vaccine')),
            ],
            options={
                'verbose_name': 'Vaccination Record',
                'verbose_name_plural': 'Vaccination Records',
                'db_table': 'vaccination_records',
                'ordering': ['-date_administered'],
                'indexes': [models.Index(fields=['dog', 'vaccine'], name='vaccination_dog_id_8bee20_idx'), models.Index(fields=['date_administered'], name='vaccination_date_ad_0b46b6_idx')],
            },
        ),
    ]
