# Generated by Django 5.2.9 on 2026-02-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author_display_name',
            field=models.CharField(blank=True, help_text='Display name for the author (defaults to username)', max_length=100),
        ),
    ]
