# Generated by Django 5.2.9 on 2026-03-02 21:07

import apps.storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_author_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmedia',
            name='file',
            field=models.FileField(upload_to='blog/media/', validators=[apps.storage.validators.validate_media_file]),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/featured/', validators=[apps.storage.validators.validate_image_file]),
        ),
    ]
