# Generated by Django 5.2.9 on 2026-03-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_stripewebhookevent_subscription_payment_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='refund_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
