# Generated by Django 5.2.9 on 2025-12-08 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Dog's name", max_length=100)),
                ('breed', models.CharField(blank=True, help_text="Dog's breed", max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MN', 'Male (Neutered)'), ('FS', 'Female (Spayed)')], default='M', help_text="Dog's sex", max_length=2)),
                ('birth_date', models.DateField(help_text="Dog's date of birth")),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text="Dog's weight in kilograms", max_digits=5, null=True)),
                ('env_indoor_only', models.BooleanField(default=False, help_text='Dog lives primarily indoors')),
                ('env_dog_parks', models.BooleanField(default=False, help_text='Dog visits dog parks regularly')),
                ('env_daycare_boarding', models.BooleanField(default=False, help_text='Dog attends daycare or boarding facilities')),
                ('env_travel_shows', models.BooleanField(default=False, help_text='Dog travels or participates in shows')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='User who owns this dog', on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dog',
                'verbose_name_plural': 'Dogs',
                'db_table': 'dogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
