# Generated by Django 5.2.9 on 2025-12-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='env_tick_exposure',
            field=models.BooleanField(default=False, help_text='Dog frequents wooded areas, tall grass, or tick-endemic regions'),
        ),
    ]
