# Generated by Django 5.2.9 on 2026-02-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_dog_env_tick_exposure'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='health_chronic_condition',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unsure', 'Not sure')], default='no', help_text='Has vet diagnosed a long-term medical condition?', max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='health_immune_condition',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unsure', 'Not sure')], default='no', help_text='Has dog been diagnosed with an immune-related condition?', max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='health_immunosuppressive_meds',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unsure', 'Not sure')], default='no', help_text='Is dog currently receiving immunosuppressive medications?', max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='health_pregnant_breeding',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('na', 'N/A')], default='no', help_text='Is dog currently pregnant or being used for breeding?', max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='health_prescription_meds',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unsure', 'Not sure')], default='no', help_text='Is dog currently taking prescription medications?', max_length=6),
        ),
        migrations.AddField(
            model_name='dog',
            name='health_vaccine_reaction',
            field=models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unsure', 'Not sure')], default='no', help_text='Has dog ever had a reaction to a vaccine?', max_length=6),
        ),
    ]
