# Generated by Django 5.2.9 on 2026-02-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_dog_health_chronic_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='medical_conditions',
            field=models.JSONField(blank=True, default=list, help_text='List of diagnosed conditions: epilepsy, autoimmune, cancer'),
        ),
        migrations.AddField(
            model_name='dog',
            name='medications',
            field=models.JSONField(blank=True, default=dict, help_text="Medications by category, e.g. {'anti_seizure': ['keppra'], 'flea_tick': ['nexgard']}"),
        ),
    ]
