# Generated by Django 5.2.9 on 2026-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_add_medical_conditions_medications'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the dog', null=True, upload_to='dogs/images/'),
        ),
    ]
