# Generated by Django 5.2.9 on 2026-03-02 21:07

import apps.storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_add_dog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the dog', null=True, upload_to='dogs/images/', validators=[apps.storage.validators.validate_image_file]),
        ),
    ]
