# Generated by Django 6.0.3 on 2026-04-14 05:47

import apps.patients.models
import apps.storage.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_dog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='DogDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.patients.models.dog_document_upload_path, validators=[apps.storage.validators.validate_document_file])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveBigIntegerField()),
                ('content_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.dog')),
            ],
            options={
                'verbose_name': 'Dog Document',
                'verbose_name_plural': 'Dog Documents',
                'db_table': 'dog_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
