# Generated by Django 6.0.3 on 2026-04-14 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_dogdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='dogdocument',
            name='extraction_data',
            field=models.JSONField(blank=True, default=dict, help_text="Tracks fields changed and vaccination records added by this document's extraction."),
        ),
    ]
