# Generated by Django 5.2.9 on 2026-02-09 20:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('patients', '0002_dog_env_tick_exposure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminders_enabled', models.BooleanField(default=False)),
                ('lead_time_days', models.PositiveIntegerField(default=7, help_text='How many days before due date to start reminding')),
                ('interval_hours', models.PositiveIntegerField(default=24, help_text='Hours between repeat reminders for the same vaccine')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder_preferences',
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_id', models.CharField(max_length=50)),
                ('dose_number', models.IntegerField(blank=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='patients.dog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reminder_logs',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'dog', 'vaccine_id', 'dose_number', 'scheduled_date'], name='idx_reminder_unique_combo'), models.Index(fields=['sent_at'], name='reminder_lo_sent_at_cf6725_idx')],
            },
        ),
    ]
