# Generated by Django 5.2.9 on 2026-02-09 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_reminderpreference_reminderlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='API endpoint that triggered the LLM call', max_length=100)),
                ('model_name', models.CharField(blank=True, default='', max_length=100)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'token_usages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='token_usage_user_id_9dec7e_idx'), models.Index(fields=['endpoint'], name='token_usage_endpoin_f46758_idx'), models.Index(fields=['created_at'], name='token_usage_created_2db800_idx')],
            },
        ),
    ]
