# Generated by Django 5.2.9 on 2026-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_tokenusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderpreference',
            name='preferred_hour',
            field=models.PositiveIntegerField(default=0, help_text='Hour of day (0-23) when the user prefers to receive emails'),
        ),
        migrations.AddField(
            model_name='reminderpreference',
            name='preferred_timezone',
            field=models.CharField(default='UTC', help_text="User's preferred timezone for email scheduling", max_length=50),
        ),
    ]
