# Generated by Django 5.2.9 on 2026-02-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_reminderpreference_preferred_hour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCapture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('source', models.CharField(default='guest_schedule', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lead_captures',
                'ordering': ['-created_at'],
            },
        ),
    ]
