# Generated by Django 5.2.11 on 2026-03-12 08:53

import apps.dashboard.models
import apps.storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_leadcapture'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Internal label for this video', max_length=255)),
                ('video_file', models.FileField(help_text='Upload MP4/WebM/Ogg — will be saved to frontend public/videos/', storage=apps.dashboard.models._get_landing_video_storage, upload_to='', validators=[apps.storage.validators.validate_video_file])),
                ('is_active', models.BooleanField(default=True, help_text='Only one video can be active. Activating this deactivates others.')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'landing_page_videos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
