# Generated by Django 5.2.11 on 2026-03-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_landingpagevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpagevideo',
            name='page_type',
            field=models.CharField(choices=[('b2c', 'B2C (Pet Owners)'), ('b2b', 'B2B (Clinics)')], default='b2c', help_text='Which landing page this video is for', max_length=3),
        ),
        migrations.AlterField(
            model_name='landingpagevideo',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Only one video can be active per page type.'),
        ),
    ]
