import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import Footer from '../components/layout/Footer';

function TermsPage() {
  return (
    <div className="app-layout">
      <motion.div
        className="legal-page"
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: -20 }}
        transition={{ duration: 0.3 }}
      >
        <div className="legal-content">
          <Link to="/home" className="legal-back-link">
            Back to Home
          </Link>

          <h1>Terms of Service</h1>
          <p className="legal-effective-date">Effective Date: January 7, 2026</p>

          <p>
            Welcome to PetVaxCalendar.com (the "Service," "Platform," "we," "us," or "our").
            By accessing or using this website and related tools, you agree to these Terms of
            Service ("Terms"). If you do not agree, please do not use the Service.
          </p>

          <h2>Informational Use Only</h2>
          <p>
            The Service provides educational and informational content only. It is intended to
            help pet owners organize and understand publicly available veterinary vaccination guidelines.
          </p>
          <p>
            The Service does not provide veterinary medical advice, diagnosis, treatment, or prescriptions.
          </p>

          <h2>No Veterinarian-Client-Patient Relationship (VCPR)</h2>
          <p>
            Use of the Service does not create a veterinarian-client-patient relationship between
            you and us or any affiliated party.
          </p>
          <p>
            All medical decisions regarding your pet must be made in consultation with a licensed veterinarian.
          </p>

          <h2>Accuracy and Guidelines</h2>
          <p>
            Vaccine schedules generated by the Service are based on generally accepted veterinary
            guidelines and user-provided information. Guidelines may change, vary by region, or
            require professional judgment.
          </p>
          <p>
            We do not guarantee that schedules are complete, up to date, or appropriate for every
            pet or jurisdiction.
          </p>

          <h2>User Responsibilities</h2>
          <p>You agree that:</p>
          <ul>
            <li>You are solely responsible for your pet's healthcare decisions</li>
            <li>You will not rely exclusively on the Service for medical or legal compliance</li>
            <li>You will consult a licensed veterinarian before administering any vaccine</li>
          </ul>

          <h2>Rabies and Legal Vaccination Requirements</h2>
          <p>
            Vaccination laws, including rabies requirements, vary by state, country, and municipality.
            The Service does not provide legal advice and does not guarantee compliance with local regulations.
          </p>

          <h2>Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, we are not liable for any direct, indirect,
            incidental, or consequential damages arising from use of the Service.
          </p>
          <p>Our total liability shall not exceed the greater of:</p>
          <ul>
            <li>The amount you paid for the Service (if any), or</li>
            <li>$100 USD</li>
          </ul>

          <h2>Indemnification</h2>
          <p>
            You agree to indemnify and hold harmless the Service and its owners from any claims,
            damages, or losses arising from your use or misuse of the Service.
          </p>

          <h2>Third-Party Services</h2>
          <p>
            The Service may integrate with third-party providers (e.g., email delivery, analytics,
            payment processors). We are not responsible for third-party content or services.
          </p>

          <h2>Changes to the Service</h2>
          <p>We may modify or discontinue the Service at any time without notice.</p>

          <h2>Governing Law</h2>
          <p>
            These Terms are governed by the laws of the State of Delaware, without regard to
            conflict-of-law principles.
          </p>

          <h2>Contact</h2>
          <p>For questions, contact:</p>
          <p>
            Email: <a href="mailto:support@petvaxcalendar.com">support@petvaxcalendar.com</a>
          </p>
        </div>
      </motion.div>
      <Footer />
    </div>
  );
}

export default TermsPage;
