# Generated by Django 5.2.9 on 2026-02-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Admin label for identification', max_length=255)),
                ('image', models.ImageField(upload_to='ads/')),
                ('link_url', models.URLField(blank=True, help_text='URL to open when ad is clicked')),
                ('position', models.CharField(choices=[('top', 'Top Banner'), ('bottom', 'Bottom Banner'), ('left', 'Left Sidebar'), ('right', 'Right Sidebar')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional start date', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional end date', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['position', 'is_active'], name='advertiseme_positio_c73b65_idx')],
            },
        ),
    ]
