# Generated by Django 5.2.9 on 2026-03-02 21:07

import apps.storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='ads/', validators=[apps.storage.validators.validate_image_file]),
        ),
    ]
