# Generated by Django 5.2.9 on 2026-02-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_set_admin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='otp_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
