# Generated by Django 5.2.9 on 2026-02-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_dashboard_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_seen_schedule_tour',
            field=models.BooleanField(default=False),
        ),
    ]
