# Generated by Django 5.2.9 on 2026-02-23 14:58

from django.db import migrations


def mark_existing_users_tour_seen(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(
        has_seen_dashboard_tour=True,
        has_seen_schedule_tour=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_tour_flags'),
    ]

    operations = [
        migrations.RunPython(
            mark_existing_users_tour_seen,
            migrations.RunPython.noop,
        ),
    ]
