# Generated by Django 5.2.9 on 2026-03-02 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_set_existing_users_tour_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pdf_exports_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
