# Generated by Django 5.2.9 on 2026-03-11 16:21

import secrets
import string

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def generate_referral_codes(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    alphabet = string.ascii_uppercase + string.digits
    existing_codes = set()
    for user in User.objects.filter(referral_code=''):
        while True:
            code = ''.join(secrets.choice(alphabet) for _ in range(8))
            if code not in existing_codes:
                break
        existing_codes.add(code)
        user.referral_code = code
        user.save(update_fields=['referral_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_pdf_exports_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingregistration',
            name='referral_code',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        # Step 1: Add referral_code without unique constraint
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, default='', help_text='Unique referral code for this user', max_length=8),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The user who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        # Step 2: Backfill referral codes for existing users
        migrations.RunPython(generate_referral_codes, migrations.RunPython.noop),
        # Step 3: Add unique constraint
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, help_text='Unique referral code for this user', max_length=8, unique=True),
        ),
    ]
