# Generated by Django 5.2.9 on 2026-03-02 22:44

import apps.storage.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short summary for listing cards', max_length=500)),
                ('video_file', models.FileField(blank=True, help_text='Upload MP4/WebM/Ogg video file (stored in R2)', null=True, upload_to='help_videos/', validators=[apps.storage.validators.validate_video_file])),
                ('video_url', models.URLField(blank=True, help_text='YouTube or external video URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='help_videos/thumbnails/', validators=[apps.storage.validators.validate_image_file])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_videos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'help_videos',
                'ordering': ['ordering', '-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='help_videos_status_165a1e_idx'), models.Index(fields=['slug'], name='help_videos_slug_75b893_idx')],
            },
        ),
    ]
